### ISSUE TITLE
Disable flex in certain environment

### ISSUE THREAD

**Issue by siuying** [ddnexus/flex#10]
In certain case I would like to disable flex in my rails model (e.g. during testing). Are there anyway I can do this? (Sorry if this is not the right place to ask)

**Comment by ddnexus** [comment]
Not sure to understand what you mean with "disable flex", but you should probably wrap the inclusion of the flex module and the `flex` call into some condition.

**Comment by siuying** [comment]
Thanks! That will do. Just wonder if there are any built-in ways.
