### ISSUE TITLE
Chaining scopes in main scope when working with ActiveRecord

### ISSUE THREAD

**Issue by BartlomiejSkwira** [ddnexus/flex#11]
Ok, I have a problem with chaining scopes inside one-aggregating scope. Here is the code:

```
class TimeLogEntry < ActiveRecord::Base
  include Flex::ModelIndexer
  flex.sync self

  def flex_source
    { id: id,
      started_at: started_at,
      stopped_at: stopped_at,
      user_id: user_id
    }
  end

  module Flex
    include ::Flex::Scopes
    flex.context = TimeLogEntry

    scope :by_user, ->(users_id) { term(user_id: users_id) }
    scope :after_timestamp, ->(started_at_timestamp) { range(started_at: { from: started_at_timestamp }) }
    scope :before_timestamp, ->(stopped_at_timestamp) { range(stopped_at: { to: stopped_at_timestamp }) }
    scope :search_time_log_entries do |user_id, started_at, stopped_at|
      result = by_user(user_id)
      result = result.after_timestamp(started_at) if started_at.present?
      result = result.before_timestamp(stopped_at) if stopped_at.present?
      result
    end
  end
```

My controller would use just the main `search_time_log_entries` scope. Using the fragment scopes works, but chaining them in the big one throws:

```
NoMethodError: undefined method `scope_methods' for #<Class:0x30848e3c>
from org/jruby/RubyBasicObject.java:1696:in `method_missing'
```

Am I doing sth wrong?

**Comment by ddnexus** [comment]
Please, post the code that calls the scope, and the full backtrace. Thanks

**Comment by BartlomiejSkwira** [comment]
So here is how I use the scopes:

```
#added 'T' to fit the elastic search time format
params[:started_at].sub(' ', 'T')
=> "2013-11-12T23:00:00"
params[:stopped_at].sub(' ', 'T')
=> "2013-11-13T23:00:00"
TimeLogEntry::Flex.after_timestamp(params[:started_at].sub(' ', 'T')).count
=> 2
TimeLogEntry::Flex.before_timestamp(params[:stopped_at].sub(' ', 'T')).count
=> 1
TimeLogEntry::Flex.by_user(10).count
=> 2

TimeLogEntry::Flex.search_time_log_entries(@current_user.id, params[:started_at].sub(' ', 'T'), params[:stopped_at].sub(' ', 'T')).count =>
NoMethodError: undefined method `scope_methods' for #<Class:0x36b8994b>
from org/jruby/RubyBasicObject.java:1497:in `method_missing'
```

Full backtrace: https://gist.github.com/BartlomiejSkwira/7447305

**Comment by BartlomiejSkwira** [comment]
The whole source code is at branch https://github.com/amberbit/KarmaTracker/tree/feature/59079612_elastic_search_for_time_log_entries

**Comment by ddnexus** [comment]
Thanks.
You discovered a bug that happens only when you use the scopes with an ActiveRecord context.
Please, update the gem to the version 1.0.5 (just pushed to rubygems)

**Comment by BartlomiejSkwira** [comment]
Yeah, I tried the same solution but got another exception:

```
NoMethodError: undefined method `after_timestamp' for #<Flex::Scope:0x17f716e7>
from org/jruby/RubyBasicObject.java:1497:in `method_missing
```

Stacktrace: https://gist.github.com/BartlomiejSkwira/7447305#file-flex-backtrace-2

**Comment by ddnexus** [comment]
True: AR scopes feature is broken at this time :/ 
Fixing it requires a little refactoring that requires a bit more thinking. I need to decide how to implement it and I hope to be able to push a new version tomorrow. Thanks.

**Comment by ddnexus** [comment]
I have pushed a new branch `refactoring/self_context`. Please, could you try it and tell me whether it solves the problem? (I have no time to test it on my own). Thanks.

**Comment by BartlomiejSkwira** [comment]
From brief testing - it works! Thank you :+1:

**Comment by ddnexus** [comment]
maybe you can use the `Flex::Conf.logger.curl_format = true` and try it in the terminal. I would double check the way you use from and to.

**Comment by BartlomiejSkwira** [comment]
Nevermind, I had bad logic used in the queries, I was using both started and stopped at dates, when I should have been using just one :rage:

**Comment by ddnexus** [comment]
Indeed, you were using `from`  and `to` from 2 different fields, so using the elasticsearch `to` and `from` defaults to actually perform the query.

**Comment by BartlomiejSkwira** [comment]
Yeah, but now I know how to get the json quries, which is useful. Thanks for all the support

**Comment by BartlomiejSkwira** [comment]
BTW: 

> Deprecated in 0.90.4.
> The from, to, include_lower and include_upper parameters have been deprecated in favour of gt,gte,lt,lte.
> http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/query-dsl-range-filter.html
