### ISSUE TITLE
Search engine (Google) on docs page sucks

### ISSUE THREAD

**Issue by BartlomiejSkwira** [ddnexus/flex#12]
I'm refering to http://ddnexus.github.io/flex/doc/1-Flex-Project/1-Overview.html - searching word 'flush' (like flush_index on the API methods page - it has 9 occurances) but the google search engine returns only 1 result - with Live Reindex page. This sucks, many times I searched for sth and had really bad results - this made me think that Flex was poorly implemented ... later to find out that there was a method I needed. 

Why not use Elastic Search for searching? ;)

**Comment by ddnexus** [comment]
I agree 100% but there are a few problems: time, time, time and time :-).

BTW, I will try to check the misconfiguration in the google indexing... my bad, due to ... time, indeed :-)
