### ISSUE TITLE
Dual search approach

### ISSUE THREAD

**Issue by charlespeach** [ddnexus/flex#16]
Hiya @ddnexus

Love the `flex` ecosystem, in the process of switching from `Tire` since we had significant problems with its implementation within our moderately complex (but content heavy) rails app.

Our application has two environments for production: `draft` and `published`. We have many different content types and page types.

The page types typically have a title, some small amount of content and finally a bunch of relationships with the different content types.

In our admin side of the application, we need to be able to search across all the different models, so content editors can quickly find previous pages and content types and edit them. This is in the draft environment.

In our public facing side of the application (published), we need the ability to search across the page types, which have many content types. So if I had an `Article` that has many `ContentItem::Reusable`s and one of the `ContentItem::Reusable`s had a title "A poll", when I search for "A poll" I need to return the parent of the content type it matches on. I.e the search result would be the `Article` not the `ContentItem::Reusable`

Could this be achieved by using the search template system in `flex`? Keeping in mind, depending on the environment were on, `draft` or `published` we need the search to behave in a slightly different way.

Also keeping in mind that a page type or content item could be both in a state of published and draft at the same time. Ie I have published a record, that record is now searchable on the published side, and it could have an updated un-published (draft) evil twin brother that shouldn't show up on the published search, but should show up in the draft search.

Can I prefix a type with something custom? Ie
- published:
  - `localhost:9393/[index_name]/published_articles/`
- draft:
  - `localhost:9393/[index_name]/articles/`

or would I be better to use a flag/boolean on the document, ie `"published": "0"` (assuming that two documents can have the same id in elastic search)?

If you have any ideas Im all for that, and thanks for taking the time to read my question.

Cheers!

**Comment by charlespeach** [comment]
@ddnexus Sorry its such a long read! My use case might be very specific to our application.. but It sure feels like it must be a common problem with a content heavy application with publishing capability.

**Comment by charlespeach** [comment]
@ddnexus Ive managed to get the switching between indexes working (I thought this would be a much cleaner approach than prefixing a status to the type). Also turns out you cant have two documents with the same type and id in elastic search, unless they have different parents.. :laughing: 

Its all uncapsulated into a rails 4 concern:

``` ruby
require 'active_support/concern'

module Indexable
  extend ActiveSupport::Concern

  module ClassMethods
  end

  def self.loaded_classes
    @loaded_classes ||= []
  end

  included do
    Indexable.loaded_classes << self

    include Flex::ModelIndexer
    flex.sync self

    after_publish :index_to_published

    def index_to_published
      flex.index = published_index
      flex.sync self
    end

    def published_index
      published_index_get
    end

    private

    def published_index_get
      app_name = "redacted"
      if Rails.env.development?
        "#{app_name}_development_published"
      elsif Rails.env.draft?
        "#{app_name}_production_published"
      end
    end
  end
end
```

This means in my `Article` I can just include `Indexable` and define the mapping on the model like so:

``` ruby
class Article < ActiveRecord::Base
  include Indexable

  def flex_source
    { title: title,
      kind: kind,
      content: content }
  end
end
```

This works a treat for publishing, as we have a custom call-back called `before_publish` and `after_publish`. Before we publish (after a draft save) it switches the index to the publish one based on the current env (so it works in development and in production).

One thing I'd love to be able to do is to centralise all of the index definitions (eg the contents of `flex_source`) as I have atleast 8 models that all need their own source config for the index. Also I'd love to be able to switch the "source" based on the index!

**Comment by aderyabin** [comment]
:+1:

**Comment by charlespeach** [comment]
@aderyabin @ddnexus In the admin side of my application, I really need to get a bunch of records back out of the database based on the ids and type that we get back from ES.. any way to do that? (scanned through all of the docs but couldn't find anything)

I could just write this myself.. something like this (btw this is terrible code, don't judge, just trying to get it working for now):

``` ruby
    if search_term.present?
      result = FlexSearch.search(:cleanable_query => params[:search_term])
    end

    @search_results = []

    result.collection.each do |document|
      @search_results << const_get(document.type.classify).find(document.id)
    end
```

(edit just found the result.collection method, so changed the code)

**Comment by charlespeach** [comment]
@aderyabin @ddnexus so I've completed the search controller for the admin side of my application, which returns me a paginated array of ActiveRecord models (and its working well!)

``` ruby
class Admin::SearchController < Admin::BaseController
  def index
    authorize! :search, :records

    search_term = params[:search_term]

    if search_term.present?
      search_results = FlexSearch.search(:cleanable_query => params[:search_term])

      model_results = []

      search_results.collection.each do |document|
        model_results << document.type
                                 .gsub("__", "::_")
                                 .camelize
                                 .constantize
                                 .find(document.id)
      end

      @search_results = Kaminari.paginate_array(model_results)
                                .page(params[:page] || 1)
                                .per(Kaminari.config.default_per_page)
    end
end
```

The only issue I have is flex is storing the type as `"content_item__reusables"` for this model `ContentItem::Reusable` so I've had to replace the undescores with `::_` for `camelize.constantize` to correctly get my models name (including the module namespace). I dont know if this is a bug in flex or not!

Now to work on the front end search.. this will be fun because I need to switch index globally to the published index, and then return the parent for every content type that matches the search term!

**Comment by ddnexus** [comment]
> One thing I'd love to be able to do is to centralise all of the index definitions (eg the contents of flex_source) as I have atleast 8 models that all need their own source config for the index. Also I'd love to be able to switch the "source" based on the index!

You probably mean switching the "mapping" (not the source).

BTW, the configuration file allows you to do all that and more.

If I understand correctly, you want to map the same type in a different way in different indices. That's easy, since you can define as many indices as you want in the configuration file, each with its own mapping and settings. Besides, you can use the anchor/alias mechanism of YAML files, so you can share mappings (or part of them) between different indices.

**Comment by ddnexus** [comment]
> I really need to get a bunch of records back out of the database based on the ids and type that we get back from ES.. any way to do that? (scanned through all of the docs but couldn't find anything)

You can do that if you use the `@result.loaded_collection`... which will load the found documents from the DB and return actual record objects.

However that is usually not a very good approach, since it requires a few extra DB queries, while using the indexed data in your view is a lot faster, but if you don't care about performance... it's there.

**Comment by charlespeach** [comment]
> You can do that if you use the @result.loaded_collection... which will load the found documents from the DB and return actual record objects.
> 
> However that is usually not a very good approach, since it requires a few extra DB queries, while using the indexed data in your view is a lot faster, but if you don't care about performance... it's there.

Sweet! Good to know I was re-inventing the wheel haha. 

On the admin side, the search index page has a bunch of buttons that do various things (like locking and unlocking a record, editing etc). For the moment, loading these back from the database (while not ideal) is the best approach while I think about the structure of the admin index. 

I could maybe store the locked status, publishing status etc etc that way I never need to hit the database!

**Comment by charlespeach** [comment]
> You probably mean switching the "mapping" (not the source).

Yep, you got it. Sorry I maybe wasnt clear enough.

> BTW, the configuration file allows you to do all that and more.
> 
> If I understand correctly, you want to map the same type in a different way in different indices. That's easy, since you can define as many indices as you want in the configuration file, each with its own mapping and settings. Besides, you can use the anchor/alias mechanism of YAML files, so you can share mappings (or part of them) between different indices.

Double yep, you got it. Thats wicked. As you said, Ideally I would have two indicies, with the same type, but with each index with its own set of mappings for the types.

Thanks for reading everything so far, its kind of turned into a blog post/mini development story.

**Comment by charlespeach** [comment]
@ddnexus I do actually need to switch the source (the attributes being index) at publish time!

eg: 

``` ruby
class Article
  include Indexable # my wrapper around including flex etc

  def flex_source
    { title: title,
      content: content,
      kind: kind }
  end
end
```

When the record gets published, I hit this method in `Indexable`: 

``` ruby
    def index_to_published
      flex.index = published_index
      flex.sync self
    end
```

What I would like to do is switch the flex_source to something more appropriate for the front end search:

``` ruby
    def flex_source
      { context: context,
        title: title,
        short_intro: short_intro,
        content: content,
        url: Rails.application.routes.url_helpers.article_path(self) }
    end
```

The requirements are that the admin section only searches on some fields, not others. The public side  (published) of the application should only return top level pages, and needs more fields.. like url and context.

I know I could probably do this with scoped/filtered searches, but it seems insane to index a document with the same fields in each index, regardless of if Im going to use them or not.

Have you had to do anything like this yet?

**Comment by ddnexus** [comment]
If you mean that you want to index different sources based on different conditions, you can include the condition in the `flex_source` method, so it will return different sources based for example on different index names:

``` ruby
def flex_source
  if flex.index == published_index
    { context: context,
      title: title,
      short_intro: short_intro,
      content: content,
      url: Rails.application.routes.url_helpers.article_path(self) }
  else
    { title: title,
      content: content,
      kind: kind }
  end
end
```
