### ISSUE TITLE
Doc infos required

### ISSUE THREAD

**Issue by lgs** [ddnexus/flex#2]
running `RAILS_ENV=production rake environment flex:import FORCE=true` I get the following error :

<pre>
watchlists index deleted
rake aborted!
no "watchlists" entry defined in /var/www/gitwatcher/config/flex.yml
Tasks: TOP => flex:import
</pre>

searching the doc I could not find a complete example, I'd be intrested in something matching Parent > Child   embedding  model described in  https://github.com/ddnexus/flex/wiki/Data-Mapping section.

In my case the file is just what `rails g flex:setup` generated by default: 

<pre>
# ANCHORS litheral key: it will not be used as template
# you can store here fragments of structures to reuse below
ANCHORS:
  -

# This is a dynamic index name The settings and mapping below will work with any index.
# The default index name generated by Flex is usually <application_name>_<environment>,
# but you may have changed it in the initializers/flex.rb or you can hardcode it if you prefer.
html_url:

  settings:
    #number_of_shards: 5
    number_of_replicas: 3

  # add your custom mappings here
  mappings: {}

</pre>

I just commented out `number_of_shards: 5` and set 3 for replica set, obviously it need some cutomization, but it's not clear to me how to do that.

A full config/flex.yml example for Parent > Child  embedding  model should be very helpful.

**Comment by ddnexus** [comment]
As a quick fix, change the 'html_url' with the  name of the index, in your case seems to be "watchlist'. Or you can just use `<%= Flex::Configuration.variables[:index] %>` which would use the default index you set in the initializer. (take a look at the comments there to know how to set it).

There is an unintended behaviour of the generator, that adds an hardcoded index name instead the more useful `<%= Flex::Configuration.variables[:index] %>`, and I should also modify a bit the initializer, so it will work out of the box. Sorry, I will do it ASAP. I added the generator just to make things easier for other people, but I didn't use it and I tested it very superficially.

Parent child relationships are managed automatically from what you declare into the model, so you usually don't have to set anything in the config file to make the parent/child work.

**Comment by ddnexus** [comment]
Fixed https://github.com/ddnexus/flex/commit/2c2cc67d0ef51c0829d582bb90145ca3e2c4b3d8
Pushed v0.4.1 to rubygems
