### ISSUE TITLE
No parent field configured on Polymorphic relationship

### ISSUE THREAD

**Issue by AlanMcCann** [ddnexus/flex#26]
I'm getting the following error when indexing my models

Flex::HttpError: /Users/alanmccann/.rvm/gems/ruby-2.1.0@givsum/gems/activerecord-4.1.4/lib/active_record/relation/batches.rb:125:in `find_in_batches'
400: {"error":"ElasticsearchIllegalArgumentException[Can't specify parent if no parent field has been configured]","status":400}

My models are as follows

B
class User
    has_one :profile_image, :as => :imageable, :dependent => :destroy
end

class Business
   has_one :profile_image, :as => :imageable, :dependent => :destroy
end

Image.rb
 belongs_to :imageable, :polymorphic => true
  include Flex::ModelIndexer
  flex.parent :imageable, 'user'   => 'user_image',
                          'business' => 'business_image'
  flex.sync self, :imageable

When I run the rake task to create the index, another parent relationship shows up in the output but not this one.

Any ideas?

Thanks

**Comment by ddnexus** [comment]
You are probably missing to sync your User and Business models. How can you have parent child relations without indexing the parents? You may want to read http://ddnexus.github.io/flex/doc/4-flex-models/2-ActiveRecord-And-Mongoid-Integration.html#elasticsearch_parentchildren_relations

**Comment by AlanMcCann** [comment]
Thanks for the response. I should have included more. I'm pretty sure I'm missing something but I do have the flex sync code for the parent models in place.

User model has the following Flex code...

  include Flex::ModelIndexer
  flex.sync self

  def flex_source
    { :id                               => id,
      :first_name                       => first_name,
      :last_name                        => last_name,
      :gender                           => gender,
      :phone                            => phone,
      :name                             => name,
      :employer_name                    => employer_name,
      :search_results_image_url => search_results_image_url,
      :link                             => link
    }
  end

Business Model has the following flex code

  include Flex::ModelIndexer
  flex.sync self

  def flex_source
    { :id                               => id,
      :name                             => name,
      :description                      => description,
      :org_type                         => org_type,
      :search_results_image_url => search_results_image_url,
      :link                             => link
    }
  end

I have another model with a single parent relationship that is working fine. It is only the polymorphic relastionship that seems to have the problem.

**Comment by ddnexus** [comment]
Then you should check the `config.flex_models`. The models have to be listed there, AND the parents must go BEFORE the children.
Also, consider to use `FORCE=true` when importing after a change like that. That will recreate the index with the new configuration.

**Comment by ddnexus** [comment]
and just a little off-topic detail: you have a typo in the url listed in your profile https://github.com/AlanMcCann

**Comment by AlanMcCann** [comment]
The issue was the config.flex models - putting them in the correct order (parents before children) worked perfectly.

Thanks for the quick responses and the work on this gem.

and thanks for the typo notification - fixed now.
