### ISSUE TITLE
Cannot search term using include Flex::ActiveModel

### ISSUE THREAD

**Issue by ChunAllen** [ddnexus/flex#27]
Hi @ddnexus, I have a record in my database table and tried to import it to flex using **rake flex:import**
I assumed that the flex:import will import the database data to flex and you can use flex scopes. I use flex's term but it doesn't return a record.

```
UserFlex.count  
```

it returns a count which is 1 
but when I use

```
UserFlex.terms(user_type: "admin").count
```

it returns 0

I'm using 

```
gem 'patron'
gem 'flex-rails'
```

I have a model **model/user.rb**

```
class User < ActiveRecord::Base
   include Flex::ModelIndexer
   flex.sync self 
   def flex_source
     {
       email: email,
       user_type: user_type
     }
   end 
end 
```

and a **user_flex.rb**

```
class UserFlex
  include Flex::ActiveModel
  flex.type = "user"
end
```

**Comment by ddnexus** [comment]
`Flex::ActiveModel` is especially designed for when you don't have a DB and want to store the data in the index itself. Instead it looks like you have one regular model synced with a DB, AND a redundant model that will read/write in the same index/type. Is that intended and what is the reason of such a setup?

Maybe it's simpler if you include the flex scopes in (a namespaced module of) the User model and use the scopes from there. Please, refer to the doc for that.

About the specific problem: check what the `FlexUser.first` returns and see if that can match exactly `'admin'`.

**Comment by ChunAllen** [comment]
Thanks @ddnexus. What I want is to have a separate model that uses flex scopes. 
because what I think the regular model which is 
**user.rb**

```
class User < ActiveRecord::Base
   include Flex::ModelIndexer 
   flex.sync self
end
```

is for accessing the DB 
and the 
**user_flex.rb**

```
class UserFlex
  include Flex::ActiveModel
  flex.type = "user"
end
```

is for accessing elasticsearch indexes.

Here's my configuration in 
**config/initializers/flex.rb**

```
  config.flex_models = %w[ User ]
  config.flex_active_models = %w[ UserFlex ]
```

can you help me if this is possible? Thanks @ddnexus

**Comment by ddnexus** [comment]
You can have what you want with just one model. You may want to read: http://ddnexus.github.io/flex/doc/3-flex-scopes/2-Scopes.html#using_flexscopes_with_activerecord_models
