### ISSUE TITLE
Terms Filter includes `nil` terms into request when `execution` is added

### ISSUE THREAD

**Issue by adimasuhid** [ddnexus/flex#29]
@ddnexus Adding `execution` to terms filter causes nil terms to be added into the request instead of being removed normally. This causes errors in the request to elastic search.

Default Filter:

```
  filter:
    and:
    - terms:
        regions: <<regions>>
```

Flex Request for nil regions:

```
 FLEX-INFO  Rendered FlexSearch.retailer from: (irb):199:in `irb_binding'
 FLEX-DEBUG  :request:
 FLEX-DEBUG    :method: GET
 FLEX-DEBUG    :path: "/development/_search"
 FLEX-DEBUG    :data:
 FLEX-DEBUG      query:
 FLEX-DEBUG        bool:
 FLEX-DEBUG          must:
 FLEX-DEBUG          - multi_match:
 FLEX-DEBUG              query: jb
 FLEX-DEBUG              fields:
 FLEX-DEBUG              - name
 FLEX-DEBUG              - abbrevation
 FLEX-DEBUG              zero_terms_query: all
```

Filter with execution:

```
  filter:
    and:
    - terms:
        regions: <<regions>>
        execution: 'and'
```

Flex request for nil regions with execution:

```
 FLEX-INFO  Rendered FlexSearch.retailer from: (irb):201:in `irb_binding'
 FLEX-DEBUG  :request:
 FLEX-DEBUG    :method: GET
 FLEX-DEBUG    :path: "/development/_search"
 FLEX-DEBUG    :data:
 FLEX-DEBUG      query:
 FLEX-DEBUG        bool:
 FLEX-DEBUG          must:
 FLEX-DEBUG          - multi_match:
 FLEX-DEBUG              query: jb
 FLEX-DEBUG              fields:
 FLEX-DEBUG              - name
 FLEX-DEBUG              - abbrevation
 FLEX-DEBUG              zero_terms_query: all
 FLEX-DEBUG      filter:
 FLEX-DEBUG        and:
 FLEX-DEBUG        - terms:
 FLEX-DEBUG            execution: and
```

**Comment by ddnexus** [comment]
Indeed, that is the expecte behaviour for your template. :)

The templating system is a generic way to interpolate variables in a data structure and prune it, depending on the values. It does not know anything about how you may want to use some "special" key.

Please, read the pruning doc for more details: http://ddnexus.github.io/flex/doc/2-flex/3-Templating/5-Interpolation.html#pruning

You may implement the behavior you want by wrapping the terms in one partial, for example by switching its inclusion on or off by passing a boolean. Please, read the partials doc for more details: http://ddnexus.github.io/flex/doc/2-flex/3-Templating/6-Partials.html#true

**Comment by ddnexus** [comment]
Another (probably simpler) alternative might be:

``` yaml
  filter:
    and:
    - terms:
        regions: <<regions>>
        execution: <<execution= ~ >>
```

then you must pass an explicit execution variable when you want to include it:

``` ruby
  YourClass.your_template(:regions => regions, :execution => (regions.blank? ? nil : 'and'))  
```

You can eventually automate the value of `:execution` by defining a template wrapper in your class (see http://ddnexus.github.io/flex/doc/2-flex/3-Templating/2-Sources.html#template_wrapper), so you can forget about passing it explicitly.

**Comment by adimasuhid** [comment]
Awesome! Will probably do your second suggestion. Thanks @ddnexus!
