### ISSUE TITLE
I'm getting "undefined method `should_prefix_index?' for Flex::LiveReindex:Module"

### ISSUE THREAD

**Issue by spodlecki** [ddnexus/flex#6]
On: "rake flex:import"

undefined method `should_prefix_index?' for Flex::LiveReindex:Module
/Users/*****/.rvm/gems/ruby-1.9.3-p429/bundler/gems/flex-7c66024bb57b/flex-models/lib/flex/model_tasks.rb:61:in`block in import_models'
/Users/****_/.rvm/gems/ruby-1.9.3-p429/bundler/gems/flex-7c66024bb57b/flex-models/lib/flex/model_tasks.rb:57:in `each'
/Users/**_**/.rvm/gems/ruby-1.9.3-p429/bundler/gems/flex-7c66024bb57b/flex-models/lib/flex/model_tasks.rb:57:in `import_models'
/Users/****_/.rvm/gems/ruby-1.9.3-p429/bundler/gems/flex-7c66024bb57b/flex-models/lib/tasks.rake:8:in `block (2 levels) in <top (required)>'
/Users/**_**/.rvm/gems/ruby-1.9.3-p429/bin/ruby_noexec_wrapper:14:in `eval'
/Users/*****/.rvm/gems/ruby-1.9.3-p429/bin/ruby_noexec_wrapper:14:in `<main>'

I'm lost. I've tried just about everything. Ideas?

Trying this as an alt to Tire... but getting this to simply index is becoming a nightmare. Any help is much appreciated... calling it a night for today.

Thanks!

**Comment by ddnexus** [comment]
Ooops, sorry, that's probably a bug due to the fact that the live-reindex module has been moved into flex-admin in a late commit. 

As a temporary fix please add the `flex-admin` gem to the `Gemfile` if you are using rails, or just require it otherwise. Please, let me know whether you can make it work. I will push a fix tomorrow.

Thanks.

**Comment by spodlecki** [comment]
No problem, adding gem 'flex-admin' did the trick, but now getting:

DEPRECATION WARNING: Requiring ruby-progressbar using `require progressbar` or `gem progressbar` has been deprecated and will be disabled on or after June 30th, 2013.  Please use `require ruby-progressbar` or `gem ruby-progressbar` instead
DEPRECATION WARNING: Calling `ProgressBar.new` is deprecated and will be removed on or after June 30th, 2013.  Please use `ProgressBar.create` instead.
DEPRECATION WARNING: Creating progress bars using ProgressBar.new(title, total, output_io) has been deprecated and will be removed on or after June 30th, 2013.  Please use ProgressBar.create(:title => title, :total => total, :output => output_io) instead. The full list of options can be found here: https://github.com/jfelchner/ruby-progressbar.
DEPRECATION WARNING: #bar_mark= will be removed on or after June 30th, 2013. Please use #progress_mark= instead.  
rake aborted!
undefined method `get_term_width' for #<ProgressBar:0/6676>
/Users/*****/.rvm/gems/ruby-1.9.3-p429/bundler/gems/flex-7c66024bb57b/flex/lib/flex/prog_bar.rb:13:in`initialize'
/Users/****_/.rvm/gems/ruby-1.9.3-p429/bundler/gems/flex-7c66024bb57b/flex-models/lib/flex/model_tasks.rb:91:in `new'
/Users/**_**/.rvm/gems/ruby-1.9.3-p429/bundler/gems/flex-7c66024bb57b/flex-models/lib/flex/model_tasks.rb:91:in `block in import_models'
/Users/****_/.rvm/gems/ruby-1.9.3-p429/bundler/gems/flex-7c66024bb57b/flex-models/lib/flex/model_tasks.rb:57:in `each'
/Users/**_**/.rvm/gems/ruby-1.9.3-p429/bundler/gems/flex-7c66024bb57b/flex-models/lib/flex/model_tasks.rb:57:in `import_models'
/Users/****_/.rvm/gems/ruby-1.9.3-p429/bundler/gems/flex-7c66024bb57b/flex-models/lib/tasks.rake:8:in `block (2 levels) in <top (required)>'
/Users/**_**/.rvm/gems/ruby-1.9.3-p429/bin/ruby_noexec_wrapper:14:in `eval'
/Users/*****/.rvm/gems/ruby-1.9.3-p429/bin/ruby_noexec_wrapper:14:in `<main>'

**Comment by ddnexus** [comment]
You have a too recent version of progress bar installed. Plaese remove it with `gem uninstall progressbar` and install an old version with `gem install progressbar -v 0.12.0`.

I will update the code to the new progressbar too. Thanks.

**Comment by ddnexus** [comment]
Just pushed the version 1.0.4 that should fix both problems. Please, let me know if it works.
